title: Magic Alt 的博客
description: 使用 GitHub Pages 与 Jekyll 搭建的个人博客。
author: Magic Alt
lang: zh-CN
timezone: Asia/Shanghai
url: ""
baseurl: ""
theme: minima
plugins:
  - jekyll-feed
permalink: /:categories/:year/:month/:day/:title/
show_excerpts: true
header_pages:
  - index.md
  - about.md
  - tags.md
