title: "Kaermaxc Blog - 日复一日"
description: "记录开发实践与思考：Neovim、C/C++、Jekyll、电机控制与自动化。分享日常开发、创意与学习笔记。"
lang: zh-CN
url: https://blog.kaermaxc.com
baseurl: ""

# 作者信息
author:
  name: Kaermaxc
  email: Kaermaxc@gmail.com  # 建议填写真实邮箱
  url: https://magic-alt.github.io

timezone: Asia/Shanghai

# 站点 Logo（用于 SEO 与社交分享）
logo: /assets/images/logo.svg

# Twitter / X 账号（可选，去掉 @）
twitter:
  username: magic_alt

# 固定链接格式
permalink: /:categories/:title/

# 分页设置
paginate: 8
paginate_path: "/page:num/"

# GitHub Pages 支持的插件
plugins:
  - jekyll-remote-theme      # 远程主题支持
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag           # 自动注入 SEO 元信息与结构化数据
  - jekyll-sitemap           # 自动生成 /sitemap.xml
  - jekyll-last-modified-at  # 自动追踪文件最后修改时间

# 远程主题（可选，注释掉则使用自定义样式）
# remote_theme: pages-themes/cayman
# 或保持当前自定义样式，注释掉上面一行

# Algolia 搜索配置（需要注册 Algolia 账号）
algolia:
  application_id: "RT6C3M3J3Y"           # Algolia Application ID
  index_name: "kaermaxc_blog"           # 索引名称
  search_only_api_key: "6c8c5e520af94e8c02707b79a7e2d610"  #  Search-Only API Key

# Talkyard 评论系统配置
talkyard:
  server_url: "https://comments-for-jekyll-demo.talkyard.net"  # 替换为你的 Talkyard 服务器
  site_id: "jekyll-demo"                                        # 替换为你的站点 ID

# Formspree 表单配置
formspree:
  form_id: "YOUR_FORM_ID"  # 替换为你的 Formspree 表单 ID

# 站长验证（填入验证码）
webmaster_verifications:
  google: ""   # Google Search Console 验证码
  bing: ""     # Bing Webmaster Tools 验证码

# Sitemap lastmod 配置
# jekyll-sitemap 会自动使用 jekyll-last-modified-at 提供的时间
# 或使用 Git 提交时间作为 lastmod

mathjax: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax

highlighter: rouge
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Kaermaxc
      toc: true

sass:
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
